### PR TITLE
Rebuild the datasource when settings change

### LINKED ISSUE #264: Grafana - Athena datasource access key rotation fails
**What happened**:
Our workflow was next:
1. We've created an IAM user + access key
2. Used this access key in Athena datasource. The datasource and Grafana dashboard started to work as expected
3. We've tried to update an access key: deleted an old one, generated a new one and updated with this new access key Athena datasource
4. After that immediately we got an error: "error querying the database: error executing query: UnrecognizedClientException: The security token included in the request is invalid. status code: 400, request id: 72b289e4-1eb5-4e57-a502-59930882c1fe"

**What you expected to happen**:
Grafana should continue to work without any issues after a new access key was applied.

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.3.1
- Plugin version: latest
- OS Grafana is installed on: on premise
- User OS & Browser: Mac OS, Chrome
- Others:

### PR DESCRIPTION
**Pull request by njvrzm**
Previously when saving settings the datasource would be partially rebuild but maintain its connection cache, so if auth-related settings changed the change would not be applied. Now the datasource will be rebuilt entirely.

Fixes #264.

### CODE REVIEW

File: pkg/main.go [hunk 1]
```diff
@@ -12,18 +15,24 @@ import (
...
+		MakeDatasourceFactory(),
 		datasource.ManageOpts{},
 	); err != nil {
 		log.DefaultLogger.Error(err.Error())
 		os.Exit(1)
 	}
 }
+
+func MakeDatasourceFactory() datasource.InstanceFactoryFunc {
+	s := athena.New()
```
Comment (iwysiu) [inline pkg/main.go:29]: Out of curiosity, is there a reason that `s` is declared outside of the return func?

**Review by iwysiu — APPROVED** [review]
Nice! I think we may have to do this in redshift too.

File: pkg/main.go (hunk 1 above)
Comment (njvrzm) [reply pkg/main.go:29]: Good question - I intended to keep part of the current behavior where the `AthenaDatasourceIface` is shared, but looking more at it I think that isn't particularly helpful, and it'll be safer not to share it. I'll move it in.

**Comment by njvrzm** [comment]
Regarding redshift, yep, same story there. I'm going to duplicate this there for now, and make a ticket to refactor it into grafana-aws-sdk later - the interfaces are a bit too tangled up to make it a quick fix.
